// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    partial class DatabaseTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.Flights", b =>
                {
                    b.Property<Guid>("FlightsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FlightID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlaneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlanesPlaneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TicketsTicketID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("passengerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("passengersID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FlightsID");

                    b.HasIndex("PlanesPlaneID");

                    b.HasIndex("TicketsTicketID");

                    b.HasIndex("passengersID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Pilots", b =>
                {
                    b.Property<Guid>("PilotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FlightHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PilotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PilotID");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Planes", b =>
                {
                    b.Property<Guid>("PlaneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Model")
                        .HasColumnType("int");

                    b.Property<Guid?>("PilotsPilotID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("int");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("registrationNumber")
                        .HasColumnType("int");

                    b.HasKey("PlaneID");

                    b.HasIndex("PilotsPilotID");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Tickets", b =>
                {
                    b.Property<Guid>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOFBooking")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FlightID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("passengerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.passengers", b =>
                {
                    b.Property<Guid>("passengersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TicketsTicketID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("passengersID");

                    b.HasIndex("TicketsTicketID");

                    b.ToTable("passengers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Flights", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Planes", null)
                        .WithMany("Flights")
                        .HasForeignKey("PlanesPlaneID");

                    b.HasOne("DatabaseTask.Core.Domain.Tickets", null)
                        .WithMany("Flights")
                        .HasForeignKey("TicketsTicketID");

                    b.HasOne("DatabaseTask.Core.Domain.passengers", null)
                        .WithMany("Flights")
                        .HasForeignKey("passengersID");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Planes", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Pilots", null)
                        .WithMany("Planes")
                        .HasForeignKey("PilotsPilotID");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.passengers", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Tickets", null)
                        .WithMany("passengers")
                        .HasForeignKey("TicketsTicketID");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Pilots", b =>
                {
                    b.Navigation("Planes");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Planes", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Tickets", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("passengers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.passengers", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
